### ISSUE TITLE
Parse error: syntax error, unexpected '='

### ISSUE THREAD

**Issue by botjv** [botjvc/botjvcphp#1]
Ligne : HbEka: $vyasQ. = $GJUCU[rand(0, $tATHT - 1)];

**Comment by botjv** [comment]
si je supprime le '=' , j'ai une autre erreur : Fatal error: Default value for parameters with a class type hint can only be NULL

`ljfjQ: function pOEtP(string $vCNNh, array $p6SIr = array(), string $pbDaI = "\107\x45\x54")`

**Comment by botjvc** [comment]
Remplace 
`$vyasQ. = $GJUCU`
par `$vyasQ .= $GJUCU`
Le point doit être à côté du égal, je ne sais pas pourquoi il s'est retrouvé là.
